services:
  postgres:
    image: postgres:16-alpine
    container_name: primum-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d:ro
    networks:
      - primum-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d core_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  core-db-migrate:
    build:
      context: ./Libs/CoreDBModel
      dockerfile: Dockerfile
    environment:
      COREDB_URL: "Host=primum-postgres;Port=5432;Database=core_db;Username=${DB_USERNAME};Password=${DB_PASSWORD};SSL Mode=Disable;"
    networks:
      - primum-network
    depends_on:
      postgres:
        condition: service_healthy

  mongodb:
    image: mongo:7
    container_name: primum-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongo-data:/data/db
    networks:
      - primum-network
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: primum-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - primum-network
    restart: unless-stopped

  telegram-bot: #у ботов контекст из корня, чтобы тянуть либки
    build:
      context: .
      dockerfile: Apps/TelegramBot/Dockerfile
    environment:
      BOTCORE_URL: "http://botcore:5000"
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@primum-rabbitmq:5672/"
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
    depends_on:
      - chat-bot-notification-service
      - botcore
    networks:
      - primum-network

  max-bot: #у ботов контекст из корня, чтобы тянуть либки
    build:
      context: .
      dockerfile: Apps/MaxBot/Dockerfile
    environment:
      BOTCORE_URL: "http://botcore:5000"
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@primum-rabbitmq:5672/"
      MAX_TOKEN: ${MAX_TOKEN}
    depends_on:
      - chat-bot-notification-service
      - botcore
    networks:
      - primum-network

  signservice:
    build:
      context: Apps/SignService
      dockerfile: Dockerfile
    container_name: sign-service
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@primum-mongodb:27017/?authSource=admin"
    networks:
      - primum-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  common-notification-service:
    build:
      context: Apps/CommonNotificationService
      dockerfile: Dockerfile
    container_name: common-notification-service
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@primum-mongodb:27017/?authSource=admin"
    networks:
      - primum-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  email-notification-service: #на самом деле зависит от ядра, хз че с этим делать
    build:
      context: Apps/EmailNotificationService
      dockerfile: Dockerfile
    container_name: email-notification-service
    environment:
      CORE_URL: "http://primumcore:5000"
      EMAIL: ${EMAIL}
      EMAIL_PASSWORD: ${EMAIL_PASSWORD}
    networks:
      - primum-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  payment-service:
    build:
      context: Apps/PaymentService
      dockerfile: Dockerfile
    container_name: payment-service
    environment:
      MONGO_URI: "mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@primum-mongodb:27017/?authSource=admin"
      MODE: "Production"
    networks:
      - primum-network
    depends_on:
      - mongodb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  chat-bot-notification-service:
    build:
      context: Apps/ChatBotNotificationService
      dockerfile: Dockerfile
    container_name: chat-bot-notification-service
    environment:
      SIGNSERVICE_URL: "http://signservice:5000"
      RABBITMQ_URL: "amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@primum-rabbitmq:5672/"
    depends_on:
      - rabbitmq
      - signservice
    networks:
      - primum-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:5000/health"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  primumcore:
    build:
      context: .
      dockerfile: Apps/PrimumCore/Dockerfile
    container_name: primumcore
    environment:
      CHATBOTNOTIFICATIONSERVICE_URL: "http://chat-bot-notification-service:5000"
      MAILNOTIFICATIONSERVICE_URL: "http://email-notification-service:5000"
      COMMONNOTIFICATIONSERVICE_URL: "http://common-notification-service:5000"
      PAYMENTSERVICE_URL: "http://payment-service:5000"
      SIGNSERVICE_URL: "http://signservice:5000"
      GATEWAY_URL: ${GATEWAY_URL}
      COREDB_URL: "Host=primum-postgres;Port=5432;Database=core_db;Username=${DB_USERNAME};Password=${DB_PASSWORD};SSL Mode=Disable;"
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_HTTP_PORTS: "5000"
    depends_on:
      core-db-migrate:
        condition: service_completed_successfully
      email-notification-service:
        condition: service_started
      chat-bot-notification-service:
        condition: service_started
      common-notification-service:
        condition: service_started
      signservice:
        condition: service_started
      payment-service:
        condition: service_started
    networks:
      - primum-network
    restart: unless-stopped

  primumwebapi:
    build:
      context: .
      dockerfile: Apps/PrimumWebAPI/Dockerfile
    container_name: primumwebapi
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      WEBAPI_JWT_ISSUER: ${WEBAPI_JWT_ISSUER}
      WEBAPI_JWT_SEED: ${WEBAPI_JWT_SEED}
      WEBAPI_JWT_AUDIENCE: ${WEBAPI_JWT_AUDIENCE}
      WEBAPI_JWT_LIFETIME_MINUTES: ${WEBAPI_JWT_LIFETIME_MINUTES}
      COMMONNOTIFICATIONSERVICE_URL: "http://common-notification-service:5000"
      PRIMUMCORE_URL: "http://primumcore:5000"
      ASPNETCORE_HTTP_PORTS: "5000"
      PAYMENTSERVICE_URL: "http://payment-service:5000"
    ports:
      - "4200:5000"
    depends_on:
      - primumcore
      - common-notification-service
    networks:
      - primum-network
    restart: unless-stopped

  botcore:
    build:
      context: .
      dockerfile: Apps/BotCore/Dockerfile
    container_name: botcore
    environment:
      SIGNSERVICE_URL: "http://signservice:5000"
      PRIMUMCORE_URL: "http://primumcore:5000"
      PAYMENTSERVICE_URL: "http://payment-service:5000"
      ASPNETCORE_HTTP_PORTS: "5000"
      GATEWAY_URL: ${GATEWAY_URL}
      ASPNETCORE_ENVIRONMENT: Production
    depends_on:
      - primumcore
      - signservice
      - payment-service
    networks:
      - primum-network
    restart: unless-stopped

  coredbiterator:
    build:
      context: .
      dockerfile: Apps/CoreDBIterator/Dockerfile
    container_name: coredbiterator
    environment:
      CHATBOTNOTIFICATIONSERVICE_URL: "http://chat-bot-notification-service:5000"
      MAILNOTIFICATIONSERVICE_URL: "http://email-notification-service:5000"
      COMMONNOTIFICATIONSERVICE_URL: "http://common-notification-service:5000"
      PAYMENTSERVICE_URL: "http://payment-service:5000"
      COREDB_URL: "Host=primum-postgres;Port=5432;Database=core_db;Username=${DB_USERNAME};Password=${DB_PASSWORD};SSL Mode=Disable;"
    depends_on:
      core-db-migrate:
        condition: service_completed_successfully
    networks:
      - primum-network
    restart: unless-stopped

  primumweb:
    build:
      context: Apps/PrimumWeb
      dockerfile: Dockerfile
    container_name: primumweb
    ports:
      - "3001:80"
    depends_on:
      - primumwebapi
    networks:
      - primum-network
    restart: unless-stopped

networks:
  primum-network:
    driver: bridge

volumes:
  postgres-data:
  rabbitmq-data:
  mongo-data: