// <auto-generated />
using System;
using CoreDBModel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreDBModel.Migrations
{
    [DbContext(typeof(PrimumContext))]
    [Migration("20260831061008_Added_Ranks")]
    partial class Added_Ranks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreDBModel.Models.Abonement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonementStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FreeLessons")
                        .HasColumnType("integer");

                    b.Property<bool>("IsReferal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<decimal>("PricePerLesson")
                        .HasColumnType("numeric");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Abonements");
                });

            modelBuilder.Entity("CoreDBModel.Models.AbonementShedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastIteration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeacherSheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbonementId");

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("AbonementShedules");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<int?>("PromoterAdminProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PromotionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PromoterAdminProfileId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("CoreDBModel.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CourseThemeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("FreeLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<string>("ReferalToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseThemeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CourseRanks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 1,
                            Rank = "Экспериментальный",
                            RequiredExperience = 0
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 2,
                            Rank = "Новаторский",
                            RequiredExperience = 2000
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 3,
                            Rank = "Базовый",
                            RequiredExperience = 4000
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 4,
                            Rank = "Проверенный временем",
                            RequiredExperience = 6000
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 5,
                            Rank = "Продвинутый",
                            RequiredExperience = 8000
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 6,
                            Rank = "Мастерский",
                            RequiredExperience = 10000
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 7,
                            Rank = "Экспертный",
                            RequiredExperience = 12000
                        },
                        new
                        {
                            Id = -8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 8,
                            Rank = "Высшей пробы",
                            RequiredExperience = 14000
                        },
                        new
                        {
                            Id = -9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 9,
                            Rank = "Флагманский",
                            RequiredExperience = 17000
                        },
                        new
                        {
                            Id = -10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 10,
                            Rank = "Легендарный",
                            RequiredExperience = 20000
                        });
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CourseThemes");
                });

            modelBuilder.Entity("CoreDBModel.Models.IncidentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevisioned")
                        .HasColumnType("boolean");

                    b.Property<int?>("Meaning")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("IncidentLogs");
                });

            modelBuilder.Entity("CoreDBModel.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentLink")
                        .HasColumnType("text");

                    b.Property<decimal?>("TeacherEarning")
                        .HasColumnType("numeric");

                    b.Property<string>("TeacherLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbonementId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CoreDBModel.Models.Promocode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoinsPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Promocodes");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentGrading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeworkGrade")
                        .HasColumnType("integer");

                    b.Property<int>("LessonActivityGrade")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("RepetitionOfMaterialGrade")
                        .HasColumnType("integer");

                    b.Property<int>("StudyInitiativeGrade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("StudentGradings");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CoinDiscount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("StudentRanks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CoinDiscount = 0f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 1,
                            Rank = "Новенький",
                            RequiredExperience = 0
                        },
                        new
                        {
                            Id = -2,
                            CoinDiscount = 0.01f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 2,
                            Rank = "Начинающий программист",
                            RequiredExperience = 2000
                        },
                        new
                        {
                            Id = -3,
                            CoinDiscount = 0.02f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 3,
                            Rank = "Любознательный ученик",
                            RequiredExperience = 4000
                        },
                        new
                        {
                            Id = -4,
                            CoinDiscount = 0.03f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 4,
                            Rank = "Уверенный кодер",
                            RequiredExperience = 6000
                        },
                        new
                        {
                            Id = -5,
                            CoinDiscount = 0.04f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 5,
                            Rank = "Разработчик-практик",
                            RequiredExperience = 8000
                        },
                        new
                        {
                            Id = -6,
                            CoinDiscount = 0.05f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 6,
                            Rank = "Опытный программист",
                            RequiredExperience = 10000
                        },
                        new
                        {
                            Id = -7,
                            CoinDiscount = 0.06f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 7,
                            Rank = "Мастер логики",
                            RequiredExperience = 12000
                        },
                        new
                        {
                            Id = -8,
                            CoinDiscount = 0.07f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 8,
                            Rank = "Виртуоз кода",
                            RequiredExperience = 14000
                        },
                        new
                        {
                            Id = -9,
                            CoinDiscount = 0.085f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 9,
                            Rank = "Гений алгоритмов",
                            RequiredExperience = 17000
                        },
                        new
                        {
                            Id = -10,
                            CoinDiscount = 0.1f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 10,
                            Rank = "Легенда школы",
                            RequiredExperience = 20000
                        });
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<float?>("ConvertionIndex")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EarningMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("TeacherRanks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0f,
                            Level = 1,
                            Rank = "Начинающий наставник",
                            RequiredExperience = 0
                        },
                        new
                        {
                            Id = -2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.02f,
                            Level = 2,
                            Rank = "Молодой ментор",
                            RequiredExperience = 2000
                        },
                        new
                        {
                            Id = -3,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.04f,
                            Level = 3,
                            Rank = "Практикующий тренер",
                            RequiredExperience = 4000
                        },
                        new
                        {
                            Id = -4,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.06f,
                            Level = 4,
                            Rank = "Опытный куратор",
                            RequiredExperience = 6000
                        },
                        new
                        {
                            Id = -5,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.08f,
                            Level = 5,
                            Rank = "Наставник-эксперт",
                            RequiredExperience = 8000
                        },
                        new
                        {
                            Id = -6,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.1f,
                            Level = 6,
                            Rank = "Учитель-виртуоз",
                            RequiredExperience = 10000
                        },
                        new
                        {
                            Id = -7,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.12f,
                            Level = 7,
                            Rank = "Мастер обучения",
                            RequiredExperience = 12000
                        },
                        new
                        {
                            Id = -8,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.14f,
                            Level = 8,
                            Rank = "Гуру алгоритмов",
                            RequiredExperience = 14000
                        },
                        new
                        {
                            Id = -9,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.17f,
                            Level = 9,
                            Rank = "Ветеран педагогики",
                            RequiredExperience = 17000
                        },
                        new
                        {
                            Id = -10,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.2f,
                            Level = 10,
                            Rank = "Легенда преподавания",
                            RequiredExperience = 20000
                        });
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherShedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherShedules");
                });

            modelBuilder.Entity("CoreDBModel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMailChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoreDBModel.Models.VerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LifeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Meaning")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("CoreDBModel.Models.Abonement", b =>
                {
                    b.HasOne("CoreDBModel.Models.Course", "Course")
                        .WithMany("Abonements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.StudentProfile", "Student")
                        .WithMany("Abonements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoreDBModel.Models.AbonementShedule", b =>
                {
                    b.HasOne("CoreDBModel.Models.Abonement", "Abonement")
                        .WithMany("AbonementShedules")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.TeacherShedule", "TeacherShedule")
                        .WithOne("AbonementShedule")
                        .HasForeignKey("CoreDBModel.Models.AbonementShedule", "TeacherSheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonement");

                    b.Navigation("TeacherShedule");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminPermission", b =>
                {
                    b.HasOne("CoreDBModel.Models.AdminProfile", "AdminProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.AdminProfile", "PromoterAdminProfile")
                        .WithMany("GivenPermissions")
                        .HasForeignKey("PromoterAdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AdminProfile");

                    b.Navigation("PromoterAdminProfile");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminProfile", b =>
                {
                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("CoreDBModel.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.Course", b =>
                {
                    b.HasOne("CoreDBModel.Models.CourseTheme", "CourseTheme")
                        .WithMany("Courses")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.CourseRank", "Rank")
                        .WithMany("Courses")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.TeacherProfile", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseTheme");

                    b.Navigation("Rank");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CoreDBModel.Models.IncidentLog", b =>
                {
                    b.HasOne("CoreDBModel.Models.AdminProfile", "AdminProfile")
                        .WithMany("IncidentLogs")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AdminProfile");
                });

            modelBuilder.Entity("CoreDBModel.Models.Lesson", b =>
                {
                    b.HasOne("CoreDBModel.Models.Abonement", "Abonement")
                        .WithMany("Lessons")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonement");
                });

            modelBuilder.Entity("CoreDBModel.Models.Promocode", b =>
                {
                    b.HasOne("CoreDBModel.Models.StudentProfile", "Student")
                        .WithMany("Promocodes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentGrading", b =>
                {
                    b.HasOne("CoreDBModel.Models.Lesson", "Lesson")
                        .WithOne("Grading")
                        .HasForeignKey("CoreDBModel.Models.StudentGrading", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentProfile", b =>
                {
                    b.HasOne("CoreDBModel.Models.StudentRank", "Rank")
                        .WithMany("Students")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("CoreDBModel.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherProfile", b =>
                {
                    b.HasOne("CoreDBModel.Models.TeacherRank", "Rank")
                        .WithMany("Teachers")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("CoreDBModel.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherShedule", b =>
                {
                    b.HasOne("CoreDBModel.Models.TeacherProfile", "Teacher")
                        .WithMany("TeacherShedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CoreDBModel.Models.VerificationToken", b =>
                {
                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.Abonement", b =>
                {
                    b.Navigation("AbonementShedules");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminProfile", b =>
                {
                    b.Navigation("GivenPermissions");

                    b.Navigation("IncidentLogs");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CoreDBModel.Models.Course", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseRank", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseTheme", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CoreDBModel.Models.Lesson", b =>
                {
                    b.Navigation("Grading");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentProfile", b =>
                {
                    b.Navigation("Abonements");

                    b.Navigation("Promocodes");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentRank", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherProfile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeacherShedules");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherRank", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherShedule", b =>
                {
                    b.Navigation("AbonementShedule");
                });

            modelBuilder.Entity("CoreDBModel.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
