// <auto-generated />
using System;
using CoreDBModel.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoreDBModel.Migrations
{
    [DbContext(typeof(PrimumContext))]
    partial class PrimumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoreDBModel.Models.Abonement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonementStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CourseId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FreeLessons")
                        .HasColumnType("integer");

                    b.Property<decimal>("PricePerLesson")
                        .HasColumnType("numeric");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Abonements");
                });

            modelBuilder.Entity("CoreDBModel.Models.AbonementShedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastIteration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TeacherSheduleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AbonementId");

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("AbonementShedules");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Permission")
                        .HasColumnType("integer");

                    b.Property<int?>("PromoterAdminProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PromotionDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PromoterAdminProfileId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("CoreDBModel.Models.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<int>("CourseThemeId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("FreeLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CourseThemeId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CourseRanks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 1,
                            Rank = "Новый",
                            RequiredExperience = 0
                        });
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("CourseThemes");
                });

            modelBuilder.Entity("CoreDBModel.Models.IncidentLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRevisioned")
                        .HasColumnType("boolean");

                    b.Property<int?>("Meaning")
                        .HasColumnType("integer");

                    b.Property<int?>("ObjectId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("IncidentLogs");
                });

            modelBuilder.Entity("CoreDBModel.Models.Lesson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StudentLink")
                        .HasColumnType("text");

                    b.Property<string>("TeacherLink")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AbonementId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CoreDBModel.Models.Promocode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CoinsPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Promocodes");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentGrading", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("HomeworkGrade")
                        .HasColumnType("integer");

                    b.Property<int>("LessonActivityGrade")
                        .HasColumnType("integer");

                    b.Property<int>("LessonId")
                        .HasColumnType("integer");

                    b.Property<int>("RepetitionOfMaterialGrade")
                        .HasColumnType("integer");

                    b.Property<int>("StudyInitiativeGrade")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("StudentGradings");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("Cash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("numeric")
                        .HasDefaultValue(0m);

                    b.Property<int>("Coins")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CoinDiscount")
                        .HasColumnType("real");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("StudentRanks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CoinDiscount = 0f,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Level = 1,
                            Rank = "Новенький",
                            RequiredExperience = 0
                        });
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Experience")
                        .HasColumnType("integer");

                    b.Property<int>("RankId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("RankId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherRank", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("EarningMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequiredExperience")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("TeacherRanks");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            EarningMultiplier = 0.3f,
                            Level = 1,
                            Rank = "Начинающий наставник",
                            RequiredExperience = 0
                        });
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherShedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("integer");

                    b.Property<int>("TeacherId")
                        .HasColumnType("integer");

                    b.Property<int>("Time")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("TeacherId");

                    b.ToTable("TeacherShedules");
                });

            modelBuilder.Entity("CoreDBModel.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMailChecked")
                        .HasColumnType("boolean");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("CoreDBModel.Models.VerificationToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LifeTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Meaning")
                        .HasColumnType("integer");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("VerificationTokens");
                });

            modelBuilder.Entity("CoreDBModel.Models.Abonement", b =>
                {
                    b.HasOne("CoreDBModel.Models.Course", "Course")
                        .WithMany("Abonements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.StudentProfile", "Student")
                        .WithMany("Abonements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoreDBModel.Models.AbonementShedule", b =>
                {
                    b.HasOne("CoreDBModel.Models.Abonement", "Abonement")
                        .WithMany("AbonementShedules")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.TeacherShedule", "TeacherShedule")
                        .WithOne("AbonementShedule")
                        .HasForeignKey("CoreDBModel.Models.AbonementShedule", "TeacherSheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonement");

                    b.Navigation("TeacherShedule");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminPermission", b =>
                {
                    b.HasOne("CoreDBModel.Models.AdminProfile", "AdminProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.AdminProfile", "PromoterAdminProfile")
                        .WithMany("GivenPermissions")
                        .HasForeignKey("PromoterAdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AdminProfile");

                    b.Navigation("PromoterAdminProfile");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminProfile", b =>
                {
                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("CoreDBModel.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.Course", b =>
                {
                    b.HasOne("CoreDBModel.Models.CourseTheme", "CourseTheme")
                        .WithMany("Courses")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.CourseRank", "Rank")
                        .WithMany("Courses")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.TeacherProfile", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseTheme");

                    b.Navigation("Rank");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CoreDBModel.Models.IncidentLog", b =>
                {
                    b.HasOne("CoreDBModel.Models.AdminProfile", "AdminProfile")
                        .WithMany("IncidentLogs")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AdminProfile");
                });

            modelBuilder.Entity("CoreDBModel.Models.Lesson", b =>
                {
                    b.HasOne("CoreDBModel.Models.Abonement", "Abonement")
                        .WithMany("Lessons")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonement");
                });

            modelBuilder.Entity("CoreDBModel.Models.Promocode", b =>
                {
                    b.HasOne("CoreDBModel.Models.StudentProfile", "Student")
                        .WithMany("Promocodes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentGrading", b =>
                {
                    b.HasOne("CoreDBModel.Models.Lesson", "Lesson")
                        .WithOne("Grading")
                        .HasForeignKey("CoreDBModel.Models.StudentGrading", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentProfile", b =>
                {
                    b.HasOne("CoreDBModel.Models.StudentRank", "Rank")
                        .WithMany("Students")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("CoreDBModel.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherProfile", b =>
                {
                    b.HasOne("CoreDBModel.Models.TeacherRank", "Rank")
                        .WithMany("Teachers")
                        .HasForeignKey("RankId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("CoreDBModel.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rank");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherShedule", b =>
                {
                    b.HasOne("CoreDBModel.Models.TeacherProfile", "Teacher")
                        .WithMany("TeacherShedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("CoreDBModel.Models.VerificationToken", b =>
                {
                    b.HasOne("CoreDBModel.Models.User", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoreDBModel.Models.Abonement", b =>
                {
                    b.Navigation("AbonementShedules");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("CoreDBModel.Models.AdminProfile", b =>
                {
                    b.Navigation("GivenPermissions");

                    b.Navigation("IncidentLogs");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("CoreDBModel.Models.Course", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseRank", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CoreDBModel.Models.CourseTheme", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("CoreDBModel.Models.Lesson", b =>
                {
                    b.Navigation("Grading");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentProfile", b =>
                {
                    b.Navigation("Abonements");

                    b.Navigation("Promocodes");
                });

            modelBuilder.Entity("CoreDBModel.Models.StudentRank", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherProfile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeacherShedules");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherRank", b =>
                {
                    b.Navigation("Teachers");
                });

            modelBuilder.Entity("CoreDBModel.Models.TeacherShedule", b =>
                {
                    b.Navigation("AbonementShedule");
                });

            modelBuilder.Entity("CoreDBModel.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
