// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimumCore.Models;

#nullable disable

namespace PrimumCore.Migrations
{
    [DbContext(typeof(PrimumContext))]
    [Migration("20250829113630_LessonLinksMayBeNull")]
    partial class LessonLinksMayBeNull
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.Property<int>("AbonementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int>("AbonementStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CourseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PaidLessons")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PricePerLesson")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StudentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbonementId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex(new[] { "AbonementId" }, "IX_Abonements_AbonementId")
                        .IsUnique();

                    b.ToTable("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.AbonementShedule", b =>
                {
                    b.Property<int>("AbonementSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int>("AbonementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("LastIteration")
                        .HasColumnType("DATETIME");

                    b.Property<int>("TeacherSheduleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AbonementSheduleId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("AbonementShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<byte[]>("Permissions")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("BLOB")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Status")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("AdminId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "AdminId" }, "IX_AdminProfiles_AdminId")
                        .IsUnique();

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FreeLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<int>("MaxLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CourseId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "CourseId" }, "IX_Courses_CourseId")
                        .IsUnique();

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int>("AbonementId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("DATETIME");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentLink")
                        .HasColumnType("TEXT");

                    b.Property<string>("TeacherLink")
                        .HasColumnType("TEXT");

                    b.HasKey("LessonId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("AbonementId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("StudentId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "StudentId" }, "IX_StudentProfiles_StudentId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("About")
                        .HasColumnType("TEXT");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeacherId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.HasIndex(new[] { "TeacherId" }, "IX_TeacherProfiles_TeacherId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.Property<int>("TeacherSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("DayOfWeek")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TeacherId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Time")
                        .HasColumnType("INTEGER");

                    b.HasKey("TeacherSheduleId")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex("TeacherId");

                    b.HasIndex(new[] { "TeacherSheduleId" }, "IX_TeacherShedules_TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("TeacherShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValueSql("0");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasAnnotation("Sqlite:Autoincrement", true);

                    b.HasIndex(new[] { "Id" }, "IX_Users_Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.HasOne("PrimumCore.Models.Course", "Course")
                        .WithMany("Abonements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.StudentProfile", "Student")
                        .WithMany("Abonements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PrimumCore.Models.AbonementShedule", b =>
                {
                    b.HasOne("PrimumCore.Models.Abonement", "Abonement")
                        .WithMany("AbonementShedules")
                        .HasForeignKey("AbonementSheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.TeacherShedule", "TeacherShedule")
                        .WithOne("AbonementShedule")
                        .HasForeignKey("PrimumCore.Models.AbonementShedule", "TeacherSheduleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonement");

                    b.Navigation("TeacherShedule");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("PrimumCore.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.HasOne("PrimumCore.Models.TeacherProfile", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.HasOne("PrimumCore.Models.Abonement", "Abonement")
                        .WithMany("Lessons")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Abonement");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("PrimumCore.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("PrimumCore.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.HasOne("PrimumCore.Models.TeacherProfile", "Teacher")
                        .WithMany("TeacherShedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.Navigation("AbonementShedules");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeacherShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.Navigation("AbonementShedule");
                });

            modelBuilder.Entity("PrimumCore.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
