// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimumCore.Models;

#nullable disable

namespace PrimumCore.Migrations
{
    [DbContext(typeof(PrimumContext))]
    [Migration("20260123183837_AddedCoinsToStudents")]
    partial class AddedCoinsToStudents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.Property<int>("AbonementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonementId"));

                    b.Property<int>("AbonementStatus")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PricePerLesson")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AbonementId");

                    b.HasIndex("AbonementId")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.AbonementShedule", b =>
                {
                    b.Property<int>("AbonementSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonementSheduleId"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastIteration")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherSheduleId")
                        .HasColumnType("int");

                    b.HasKey("AbonementSheduleId");

                    b.HasIndex("AbonementId");

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("AbonementShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminPermission", b =>
                {
                    b.Property<int>("AdminPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPermissionId"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int?>("PromoterAdminProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PromotionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminPermissionId");

                    b.HasIndex("AdminPermissionId")
                        .IsUnique();

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("PromoterAdminProfileId");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("AdminId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("int");

                    b.Property<int>("CourseThemeId")
                        .HasColumnType("int");

                    b.Property<int>("FreeLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.HasIndex("CourseThemeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("PrimumCore.Models.CourseTheme", b =>
                {
                    b.Property<int>("CourseThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseThemeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseThemeId");

                    b.HasIndex("CourseThemeId")
                        .IsUnique();

                    b.ToTable("CourseThemes");
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("AbonementId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("int");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("int");

                    b.Property<float>("EarningMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.Property<int>("TeacherSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherSheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("TeacherSheduleId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("TeacherShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Cash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.HasOne("PrimumCore.Models.Course", "Course")
                        .WithMany("Abonements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.StudentProfile", "Student")
                        .WithMany("Abonements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PrimumCore.Models.AbonementShedule", b =>
                {
                    b.HasOne("PrimumCore.Models.Abonement", "Abonement")
                        .WithMany("AbonementShedules")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.TeacherShedule", "TeacherShedule")
                        .WithOne("AbonementShedule")
                        .HasForeignKey("PrimumCore.Models.AbonementShedule", "TeacherSheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonement");

                    b.Navigation("TeacherShedule");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminPermission", b =>
                {
                    b.HasOne("PrimumCore.Models.AdminProfile", "AdminProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.AdminProfile", "PromoterAdminProfile")
                        .WithMany("GivenPermissions")
                        .HasForeignKey("PromoterAdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AdminProfile");

                    b.Navigation("PromoterAdminProfile");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("PrimumCore.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.HasOne("PrimumCore.Models.CourseTheme", "CourseTheme")
                        .WithMany("Courses")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.TeacherProfile", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseTheme");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.HasOne("PrimumCore.Models.Abonement", "Abonement")
                        .WithMany("Lessons")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonement");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("PrimumCore.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("PrimumCore.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.HasOne("PrimumCore.Models.TeacherProfile", "Teacher")
                        .WithMany("TeacherShedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.Navigation("AbonementShedules");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.Navigation("GivenPermissions");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.CourseTheme", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeacherShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.Navigation("AbonementShedule");
                });

            modelBuilder.Entity("PrimumCore.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
