// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PrimumCore.Models;

#nullable disable

namespace PrimumCore.Migrations
{
    [DbContext(typeof(PrimumContext))]
    partial class PrimumContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.Property<int>("AbonementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonementId"));

                    b.Property<int>("AbonementStatus")
                        .HasColumnType("int");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("PricePerLesson")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.HasKey("AbonementId");

                    b.HasIndex("AbonementId")
                        .IsUnique();

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.ToTable("Abonements", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.AbonementShedule", b =>
                {
                    b.Property<int>("AbonementSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AbonementSheduleId"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastIteration")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeacherSheduleId")
                        .HasColumnType("int");

                    b.HasKey("AbonementSheduleId");

                    b.HasIndex("AbonementId");

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("AbonementShedules", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.AdminPermission", b =>
                {
                    b.Property<int>("AdminPermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminPermissionId"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("int");

                    b.Property<int>("Permission")
                        .HasColumnType("int");

                    b.Property<int?>("PromoterAdminProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PromotionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("AdminPermissionId");

                    b.HasIndex("AdminPermissionId")
                        .IsUnique();

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("PromoterAdminProfileId");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("AdminId");

                    b.HasIndex("AdminId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("AdminProfiles", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("int");

                    b.Property<int>("CourseThemeId")
                        .HasColumnType("int");

                    b.Property<int>("FreeLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("MaxLessons")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseId")
                        .IsUnique();

                    b.HasIndex("CourseThemeId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.CourseTheme", b =>
                {
                    b.Property<int>("CourseThemeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseThemeId"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CourseThemeId");

                    b.HasIndex("CourseThemeId")
                        .IsUnique();

                    b.ToTable("CourseThemes", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.IncidentLog", b =>
                {
                    b.Property<int>("LogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LogId"));

                    b.Property<int>("AdminProfileId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DecisionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsRevisioned")
                        .HasColumnType("bit");

                    b.HasKey("LogId");

                    b.HasIndex("AdminProfileId");

                    b.HasIndex("LogId")
                        .IsUnique();

                    b.ToTable("IncidentLogs", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LessonId"));

                    b.Property<int>("AbonementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("StudentLink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TeacherLink")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LessonId");

                    b.HasIndex("AbonementId");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.ToTable("Lessons", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.Promocode", b =>
                {
                    b.Property<int>("PromocodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PromocodeId"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CoinsPrice")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PromocodeId");

                    b.HasIndex("PromocodeId")
                        .IsUnique();

                    b.HasIndex("StudentId");

                    b.ToTable("Promocodes", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.StudentGrading", b =>
                {
                    b.Property<int>("StudentGradingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentGradingId"));

                    b.Property<int>("HomeworkGrade")
                        .HasColumnType("int");

                    b.Property<int>("LessonActivityGrade")
                        .HasColumnType("int");

                    b.Property<int>("LessonId")
                        .HasColumnType("int");

                    b.Property<int>("RepetitionOfMaterialGrade")
                        .HasColumnType("int");

                    b.Property<int>("StudyInitiativeGrade")
                        .HasColumnType("int");

                    b.HasKey("StudentGradingId");

                    b.HasIndex("LessonId")
                        .IsUnique();

                    b.HasIndex("StudentGradingId")
                        .IsUnique();

                    b.ToTable("StudentGrading", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("int");

                    b.Property<int>("Coins")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("StudentId");

                    b.HasIndex("StudentId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("StudentProfiles", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.Property<int>("TeacherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherId"));

                    b.Property<string>("About")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ApproveStatus")
                        .HasColumnType("int");

                    b.Property<float>("EarningMultiplier")
                        .HasColumnType("real");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TeacherId");

                    b.HasIndex("TeacherId")
                        .IsUnique();

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("TeacherProfiles", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.Property<int>("TeacherSheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeacherSheduleId"));

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<int>("Time")
                        .HasColumnType("int");

                    b.HasKey("TeacherSheduleId");

                    b.HasIndex("TeacherId");

                    b.HasIndex("TeacherSheduleId")
                        .IsUnique();

                    b.ToTable("TeacherShedules", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("Cash")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<bool>("IsBanned")
                        .HasColumnType("bit");

                    b.Property<bool>("IsMailChecked")
                        .HasColumnType("bit");

                    b.Property<string>("MailAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patronymic")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.VerificationToken", b =>
                {
                    b.Property<int>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TokenId"));

                    b.Property<bool>("IsUsed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LifeTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Meaning")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("TokenId");

                    b.HasIndex("TokenId")
                        .IsUnique();

                    b.HasIndex("UserId");

                    b.ToTable("VerificationTokens", (string)null);
                });

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.HasOne("PrimumCore.Models.Course", "Course")
                        .WithMany("Abonements")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.StudentProfile", "Student")
                        .WithMany("Abonements")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PrimumCore.Models.AbonementShedule", b =>
                {
                    b.HasOne("PrimumCore.Models.Abonement", "Abonement")
                        .WithMany("AbonementShedules")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.TeacherShedule", "TeacherShedule")
                        .WithOne("AbonementShedule")
                        .HasForeignKey("PrimumCore.Models.AbonementShedule", "TeacherSheduleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonement");

                    b.Navigation("TeacherShedule");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminPermission", b =>
                {
                    b.HasOne("PrimumCore.Models.AdminProfile", "AdminProfile")
                        .WithMany("Permissions")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.AdminProfile", "PromoterAdminProfile")
                        .WithMany("GivenPermissions")
                        .HasForeignKey("PromoterAdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AdminProfile");

                    b.Navigation("PromoterAdminProfile");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("AdminProfile")
                        .HasForeignKey("PrimumCore.Models.AdminProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.HasOne("PrimumCore.Models.CourseTheme", "CourseTheme")
                        .WithMany("Courses")
                        .HasForeignKey("CourseThemeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PrimumCore.Models.TeacherProfile", "Teacher")
                        .WithMany("Courses")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseTheme");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PrimumCore.Models.IncidentLog", b =>
                {
                    b.HasOne("PrimumCore.Models.AdminProfile", "AdminProfile")
                        .WithMany("IncidentLogs")
                        .HasForeignKey("AdminProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AdminProfile");
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.HasOne("PrimumCore.Models.Abonement", "Abonement")
                        .WithMany("Lessons")
                        .HasForeignKey("AbonementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Abonement");
                });

            modelBuilder.Entity("PrimumCore.Models.Promocode", b =>
                {
                    b.HasOne("PrimumCore.Models.StudentProfile", "Student")
                        .WithMany("Promocodes")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentGrading", b =>
                {
                    b.HasOne("PrimumCore.Models.Lesson", "Lesson")
                        .WithOne("Grading")
                        .HasForeignKey("PrimumCore.Models.StudentGrading", "LessonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lesson");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("StudentProfile")
                        .HasForeignKey("PrimumCore.Models.StudentProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithOne("TeacherProfile")
                        .HasForeignKey("PrimumCore.Models.TeacherProfile", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.HasOne("PrimumCore.Models.TeacherProfile", "Teacher")
                        .WithMany("TeacherShedules")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("PrimumCore.Models.VerificationToken", b =>
                {
                    b.HasOne("PrimumCore.Models.User", "User")
                        .WithMany("VerificationTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("PrimumCore.Models.Abonement", b =>
                {
                    b.Navigation("AbonementShedules");

                    b.Navigation("Lessons");
                });

            modelBuilder.Entity("PrimumCore.Models.AdminProfile", b =>
                {
                    b.Navigation("GivenPermissions");

                    b.Navigation("IncidentLogs");

                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("PrimumCore.Models.Course", b =>
                {
                    b.Navigation("Abonements");
                });

            modelBuilder.Entity("PrimumCore.Models.CourseTheme", b =>
                {
                    b.Navigation("Courses");
                });

            modelBuilder.Entity("PrimumCore.Models.Lesson", b =>
                {
                    b.Navigation("Grading");
                });

            modelBuilder.Entity("PrimumCore.Models.StudentProfile", b =>
                {
                    b.Navigation("Abonements");

                    b.Navigation("Promocodes");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherProfile", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("TeacherShedules");
                });

            modelBuilder.Entity("PrimumCore.Models.TeacherShedule", b =>
                {
                    b.Navigation("AbonementShedule");
                });

            modelBuilder.Entity("PrimumCore.Models.User", b =>
                {
                    b.Navigation("AdminProfile");

                    b.Navigation("StudentProfile");

                    b.Navigation("TeacherProfile");

                    b.Navigation("VerificationTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
